name: Build Windows

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          arch: 'win64_msvc2019_64'

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake SrtToContinuityListConverter.pro
          nmake

      - name: Deploy Qt dependencies
        shell: cmd
        run: |
          mkdir deploy
          copy release\SrtToContinuityListConverter.exe deploy\
          windeployqt --release deploy\SrtToContinuityListConverter.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SrtToContinuityListConverter-windows
          path: deploy\